CREATE TABLE (
  "Opportunity" TITLE,
  "Company" RICH_TEXT,
  "Country" SELECT('Malaysia':green, 'Philippines':blue, 'Thailand':yellow, 'Vietnam':orange, 'Singapore':purple, 'Japan':pink, 'Korea':red, 'Other':gray),
  "City" RICH_TEXT,
  "Role Family" SELECT('Korean Customer Support':blue, 'Korean Travel Operations':green, 'Reservations Operations':green, 'Customer Operations':blue, 'Escalation':orange, 'Quality Assurance':purple, 'SME / Floor Support':purple, 'Training':yellow, 'Workforce Management':red, 'Real-Time Operations':red, 'Partner Support':brown, 'Vendor Operations':brown, 'Customer Success Operations':pink, 'Trust and Safety Operations':gray, 'Content Operations':gray, 'Operations Coordination':blue, 'Other':default),
  "Seniority" SELECT('Associate':gray, 'Senior Associate':blue, 'Specialist':green, 'Senior Specialist':green, 'SME':purple, 'Analyst':orange, 'Team Lead':yellow, 'Manager':red, 'Unknown':default),
  "Korean Requirement" SELECT('Required':green, 'Preferred':blue, 'Not stated':yellow, 'Not required':gray),
  "English Requirement" RICH_TEXT,
  "Work Authorization" SELECT('Candidate eligible':green, 'Sponsorship available':blue, 'Local work rights required':yellow, 'Local nationals only':red, 'Unknown':gray),
  "Visa Sponsorship" SELECT('Yes':green, 'Available':blue, 'No':red, 'Unknown':gray, 'Not applicable':default),
  "Work Mode" SELECT('On-site':blue, 'Hybrid':green, 'Remote':purple, 'Unknown':gray),
  "Employment Type" SELECT('Permanent full time':green, 'Full time contract':blue, 'Temporary':yellow, 'Part time':orange, 'Casual':gray, 'Unknown':default),
  "Shift Pattern" RICH_TEXT,
  "Experience Requirement" RICH_TEXT,
  "Salary" RICH_TEXT,
  "Currency" SELECT('MYR':green, 'PHP':blue, 'THB':yellow, 'VND':orange, 'SGD':purple, 'JPY':pink, 'KRW':red, 'USD':gray, 'Other':default),
  "Source URL" URL,
  "Source Type" SELECT('Company career site':green, 'LinkedIn':blue, 'JobStreet':orange, 'Indeed':purple, 'Recruiter':yellow, 'Other':gray),
  "Posted Date" DATE,
  "Freshness Days" NUMBER,
  "Vacancy Status" SELECT('Live':green, 'Needs recheck':yellow, 'Unknown':gray, 'Closed':red, 'Expired':red),
  "Evidence Text" RICH_TEXT,
  "Evidence Grade" SELECT('A':green, 'B':blue, 'C':yellow, 'D':red),
  "Career Transfer Score" NUMBER,
  "Hiring Reality Score" NUMBER,
  "Strategic Value Score" NUMBER,
  "Final Priority Score" NUMBER,
  "Red Team Verdict" SELECT('PASS':green, 'HOLD':yellow, 'REJECT':red),
  "Apply Status" STATUS,
  "CV Variant" SELECT('Korean Customer Support':blue, 'Travel / Reservations Operations':green, 'Escalation / Senior Specialist':orange, 'QA / SME / Trainer':purple, 'Workforce / Real-Time Operations':red, 'Partner / Vendor Support':brown, 'Not selected':gray),
  "Hard Gate Reason" RICH_TEXT,
  "Canonical Key" RICH_TEXT,
  "Company Research Status" SELECT('Not started':gray, 'Researching':yellow, 'Verified':green, 'Risk found':red),
  "Company Risk" RICH_TEXT,
  "Next Action" RICH_TEXT,
  "Last Verified" DATE
);
